---
name: El Jefe CLA
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
permissions:
  actions: read
  contents: read
  pull-requests: write
  statuses: write
jobs:
  el-jefe-cla:
    name: El Jefe CLA
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      pull-requests: write
      statuses: write
    steps:
      - name: Run El Jefe Contributor License Agreement (CLA) assistant
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have hereby read the El Jefe CLA and agree to its terms') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@ca4a40a7d1004f18d9960b404b97e5f30a505a08 # v2.6.1
        with:
          # Path to the CLA document.
          path-to-document: https://github.com/plethoraofpinatas/turbo-umbrella/blob/main/el-jefe-cla.md
          # Custom CLA messages.
          custom-notsigned-prcomment: 'ðŸŽ‰ Thank you for your contribution! It appears you have not yet signed the [El Jefe Contributor License Agreement (CLA)](https://github.com/plethoraofpinatas/turbo-umbrella/blob/main/el-jefe-cla.md), which is required for your changes to be incorporated into an El Jefe Open Source Software (OSS) project. Please kindly read the [El Jefe CLA](https://github.com/plethoraofpinatas/turbo-umbrella/blob/main/el-jefe-cla.md) and reply on a new comment with the following text to agree:'
          custom-pr-sign-comment: 'I have hereby read the El Jefe CLA and agree to its terms'
          custom-allsigned-prcomment: 'ðŸ”¥ðŸ”¥ðŸ”¥ All required contributors have signed the El Jefe CLA for this PR. Thank you! ðŸ”¥ðŸ”¥ðŸ”¥'
          # Remote repository storing CLA signatures.
          remote-organization-name: plethoraofpinatas
          remote-repository-name: cla-signatures
          # Branch where CLA signatures are stored.
          branch: main
          path-to-signatures: signatures/signatures.json
          # Comma separated list of usernames for maintainers or any other individuals who should not be prompted for a CLA.
          # NOTE: You will want to edit the usernames to suit your project needs.
          allowlist: Copilot,dependabot[bot],renovate[bot]
          # Do not lock PRs after a merge.
          lock-pullrequest-aftermerge: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.EL_JEFE_CLA_TOKEN }}
